//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.25 at 10:42:52 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dhis2.org/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.hisp.dhis.ws;
